# Generated by Django 3.2.8 on 2021-11-01 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app_accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
