# Generated by Django 3.2.8 on 2021-11-02 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app_accounts', '0003_order_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='product',
            name='destcription',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='tags',
            field=models.ManyToManyField(to='crm_app_accounts.Tag'),
        ),
    ]
